---
# tasks file for kvm_provision
- name: Display vm name
  ansible.builtin.debug:
    var: vm_name

- name: Provision vm tasks
  ansible.builtin.import_tasks: 01_tasks_provision.yml

- name: Ensure vm is started
  community.libvirt.virt:
    name: "{{ vm_name }}"
    state: running
  register: vm_start_results
  until: "vm_start_results is success"
  retries: 15
  delay: 2

- name: Connect host to guest vm tasks
  ansible.builtin.import_tasks: 02_tasks_connect.yml
  when: vm_start_results is success
